import type { Metadata, Viewport } from "next";
import { cookies } from "next/headers";
import { previewEnabled } from "@/lib/preview";
import { getSessionUser } from "@/lib/session";
import { listInvitesForEmail } from "@/server/groups";
import { NoticeOverlay } from "./notice-overlay";
import { ConsentGate } from "./consent-gate";
import { PreviewBar } from "./preview-bar";
import { TabBar } from "./nav";
import "./globals.css";

/**
 * Where a relative URL in this metadata resolves to.
 *
 * Without it Next warns and falls back to localhost, which would put
 * `http://localhost:3000/...` in the link preview of every message anybody
 * ever sends. `BETTER_AUTH_URL` is already per-environment and already the
 * origin the app is served from, so dev previews as dev and production as
 * production without a second variable to keep in step.
 */
const ORIGIN = process.env.BETTER_AUTH_URL ?? "https://curfew.amanarya.com";

export const metadata: Metadata = {
  metadataBase: new URL(ORIGIN),
  // A template, so every screen can name itself and still carry the app.
  // `default` is what the sign-in page and anything without its own title get.
  title: {
    default: "Curfew",
    template: "%s · Curfew",
  },
  description:
    "Track what you said you would do, and prove it. Photo evidence, a streak per habit, and private groups that only see what you share.",
  applicationName: "Curfew",
  // The one page a stranger can reach is the sign-in page, and it is the only
  // thing worth indexing: everything else answers 307 to a signed-out request,
  // so a crawler would only ever collect redirects. `robots.ts` says the same
  // thing in the file crawlers actually read.
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, "max-image-preview": "large" },
  },
  // What a link to Curfew looks like when it is pasted into a chat, which is
  // exactly how an invite reaches somebody.
  openGraph: {
    type: "website",
    siteName: "Curfew",
    title: "Curfew",
    description:
      "Track what you said you would do, and prove it. Invite only.",
    url: "/",
  },
  twitter: {
    card: "summary_large_image",
    title: "Curfew",
    description: "Track what you said you would do, and prove it. Invite only.",
  },
  // Installed on iOS: no browser chrome, and light text on a dark status bar,
  // which is what a near-black app wants.
  //
  // `black`, not `black-translucent`, on purpose. Translucent draws the page
  // UNDER the clock, so every screen would need `env(safe-area-inset-top)` or
  // its heading would sit behind the time and the battery. This reserves the
  // strip instead, at #000 against a #0b0a09 app, which is a difference nobody
  // can see. The bottom is the one that still needs handling, because the home
  // indicator floats over the page whatever this says (see `.pb-nav`).
  appleWebApp: {
    capable: true,
    title: "Curfew",
    statusBarStyle: "black",
  },
  // Safari turns anything that looks like a phone number into a link, which on
  // this app means times and streak counts.
  formatDetection: { telephone: false, date: false, address: false, email: false },
  other: {
    // Next emits only `mobile-web-app-capable`, the spelling that replaced
    // this one. iOS before 16.4 reads the prefixed name and nothing else, and
    // an iPhone that does not see it opens the home-screen icon in Safari with
    // the URL bar showing rather than as an app. Both cost one tag.
    "apple-mobile-web-app-capable": "yes",
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  // The page is drawn behind the notch and the home indicator, which is what
  // makes an installed app look like one. Everything fixed to an edge pays for
  // it with an `env(safe-area-inset-*)`.
  viewportFit: "cover",
  themeColor: [
    { media: "(prefers-color-scheme: dark)", color: "#0b0a09" },
    { media: "(prefers-color-scheme: light)", color: "#e8e6e1" },
  ],
};

/**
 * iOS launch images.
 *
 * Android takes its splash from the manifest. iOS takes it only from these,
 * and only when the media query matches the device EXACTLY: a miss is a white
 * screen on every cold start, which on a near-black app is the most visible
 * thing it could do. Generated by `bun run make:icons`, which owns this list.
 *
 * Rendered as elements rather than through the metadata API, which has no
 * field for them. React hoists a <link> into the head from anywhere.
 */
const SPLASH = [
  { w: 440, h: 956, s: 3 },
  { w: 402, h: 874, s: 3 },
  { w: 430, h: 932, s: 3 },
  { w: 393, h: 852, s: 3 },
  { w: 428, h: 926, s: 3 },
  { w: 390, h: 844, s: 3 },
  { w: 375, h: 812, s: 3 },
  { w: 414, h: 896, s: 3 },
  { w: 414, h: 896, s: 2 },
  { w: 375, h: 667, s: 2 },
];

function SplashLinks() {
  return (
    <>
      {SPLASH.map(({ w, h, s }) => (
        <link
          key={`${w}x${h}@${s}`}
          rel="apple-touch-startup-image"
          media={`(device-width: ${w}px) and (device-height: ${h}px) and (-webkit-device-pixel-ratio: ${s})`}
          href={`/splash/splash-${w}x${h}@${s}x.png`}
        />
      ))}
    </>
  );
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Default dark. Read the cookie server-side so SSR stamps the chosen theme and
  // there is no flash on load. The switch itself lives in Settings.
  const theme =
    (await cookies()).get("theme")?.value === "light" ? "light" : "dark";

  // The tab bar's own pending-invite dot (decision 33). A signed-out or
  // pending-approval visitor never has one, and the bar itself is hidden on
  // their routes anyway.
  const user = await getSessionUser();
  const invites = user ? await listInvitesForEmail(user.email) : [];

  return (
    <html lang="en" data-theme={theme} suppressHydrationWarning>
      <head>
        {/* The weight most of a screen is set in. Preloaded because it is
            discovered inside a stylesheet otherwise, which costs a round trip
            before any text can settle. The rest are fetched when used. */}
        <link
          rel="preload"
          as="font"
          type="font/woff2"
          href="/fonts/ibm-plex-mono-400-latin.woff2"
          crossOrigin="anonymous"
        />
        <SplashLinks />
      </head>
      <body>
        {children}
        <TabBar hasPendingInvite={invites.length > 0} />
        <ConsentGate />
        <NoticeOverlay />
        {previewEnabled() ? <PreviewBar /> : null}
      </body>
    </html>
  );
}
